### ISSUE TITLE
Missing Option monolog in config type

### ISSUE THREAD

**Issue by kurtjunker** [getsentry/sentry-symfony#443] opened 2021-02-15 08:38 UTC
Hi,

I tried to use your new Version 4.0.1 for Symfony. But it is not working if I want to use monolog as error_handler. 

Symfony: 5.1
Monolog-Bundle: 3.6
Sentry-Symfony: 4.0

I got the Error: `Unrecognized option "monolog" under "sentry". Available options are "dsn", "messenger", "options", "register_error_listener".`

I think it is related to the "new" schema. There is no entry for the monolog option.

https://github.com/getsentry/sentry-symfony/blob/172a4f283bc6f218db51692189a62796585b693b/src/Resources/config/schema/sentry-1.0.xsd#L10

If I am wrong please do not hesitate to tell me how can I implement the monolog error_handler with Sentry-Symfony version >4.0

**Comment by ste93cry** [comment] 2021-02-15 13:01
Duplicate of #441. Documentation and README need to be updated, sorry about that.

>how can I implement the monolog error_handler with Sentry-Symfony version >4.0

You can find some information in the `UPGRADE-4.0.md` file: basically, you just have to define the Monolog handler as a service and then use it in the `monolog` config as any other handler you may have

**Closed by ste93cry** 2021-02-15 13:01 UTC
Labels: Type: Question
