### ISSUE TITLE
Breaking versions with composer/package-versions-deprecated

### ISSUE THREAD

**Issue by NikitaKharkov** [getsentry/sentry-symfony#346] opened 2020-05-25 14:36 UTC
So, I can't update this package to 3.5 because of using this package. This package is installed automatically to version 1.8 (current and the single one), so can't remove it or do something with it. At the same, time your package has the dependency:
```
    "conflict": {
        "ocramius/package-versions": "<1.3"
    },
```
Can you fix it? Or can you advise me on what to do?

**Comment by Jean85** [comment] 2020-05-25 16:57
First thing, you should try and check if you're using the latest Composer patch, 1.10.6, which contains a fix for resolving the dependecies of `jean85/pretty-package-versions`, which in turn requires `ocramius/package-versions`. 

You should be able to install 3.5 without issues then. But, nonetheless, we should drop that requirement somehow, because it's better to use the native Composer 2 support in the future.

**Comment by jakub-frajt** [comment] 2020-06-08 11:05
Even with latest version of Composer (1.10.7) it's not possible to install this package.

**Comment by Jean85** [comment] 2020-06-08 11:11
Can you share a `composer.json` that reproduces this issue? I cannot understand why you can't, the constraints shouldn't create any issue.

**Comment by Jean85** [comment] 2020-06-19 14:17
As pointed out by #347, there was an underlying issue, but it has been fixed with https://github.com/composer/package-versions-deprecated/pull/3.

Closing as fixed, feel free to reply or reopen if it still doesn't work.

**Closed by Jean85** 2020-06-19 14:17 UTC
Labels: support
