### ISSUE TITLE
Upgrade to sentry/sentry:^4.0

### ISSUE THREAD

**Issue by joanna-bak-sourceability** [getsentry/sentry-symfony#795] opened 2023-12-22 13:16 UTC
### Problem Statement

sentry/sentry:^3.0 is using not supported packages like php-http/message-factory. 

### Solution Brainstorm

add sentry/sentry:^4.0

**Comment by cleptric** [comment] 2023-12-22 15:00
Duplicate of https://github.com/getsentry/sentry-symfony/issues/783

**Closed by cleptric** 2023-12-22 15:00 UTC
Labels: Waiting for: Product Owner
