### ISSUE TITLE
Fatal error: Declaration of Sentry\Monolog\Handler::write(array $record): void must be compatible with Monolog\Handler\AbstractProcessingHandler::write(Monolog\LogRecord $record): void

### ISSUE THREAD

**Issue by teol** [getsentry/sentry-symfony#640] opened 2022-05-31 17:12 UTC
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
PHP 8.1
Symfony 6.1
sentry/sentry 3.5.0
sentry/sdk 3.2.0
sentry/sentry-symfony 4.3.0

### Steps to Reproduce

On a Symfony 6.1 app:
1. composer require sentry/sentry-symfony
2. Add DSN config etc
3. Add to monolog config:
```
monolog:
    handlers:
        sentry:
            type: sentry
            level: !php/const Monolog\Logger::ERROR
            hub_id: Sentry\State\HubInterface
```

### Expected Result

Nothing special, the Symfony app should work.

### Actual Result

Fatal error: Declaration of Sentry\Monolog\Handler::write(array $record): void must be compatible with Monolog\Handler\AbstractProcessingHandler::write(Monolog\LogRecord $record): void in /srv/app/vendor/sentry/sentry/src/Monolog/Handler.php on line 51

### Other
I had no issue with my project using Symfony 6.0. I suspect that this issue is caused by Symfony upgrade to version 6.1. Or maybe I'm wrong and I'm just missing something.

**Comment by teol** [comment] 2022-05-31 17:18
Found that an issue is already created on the PHP SDK repository: https://github.com/getsentry/sentry-php/issues/1318

Any way I can get my app to work with the handler?

**Comment by Jean85** [comment] 2022-06-01 15:48
This is already solved with https://github.com/getsentry/sentry-php/pull/1321, which is not released yet, unfortunately.

**Comment by Tofandel** [comment] 2022-06-09 09:40
Well the issue is that this makes it incompatible with symfony 6.1 because Monolog v2 only supports symfony 3 and lower, what's weird I I didn't have this issue in 6.0 and got it when I wanted to upgrade from symfony 6.0 to 6.1

**Comment by ste93cry** [comment] 2022-06-10 23:00
A new minor version of the core SDK just got released with support for Monolog 3 🎉 I'm gonna close this as the issue should be solved by updating the `sentry/sentry` package

**Closed by ste93cry** 2022-06-10 23:00 UTC
