### ISSUE TITLE
Sentry bundle breaks Symfony cache adapter

### ISSUE THREAD

**Issue by Jeroeny** [getsentry/sentry-symfony#530] opened 2021-07-06 14:54 UTC
### Environment

PHP: 8.0.8
Sentry dependencies installed via composer 2.1.3:

- sentry/sdk  3.1.0   
- sentry/sentry 3.3.1
- sentry/sentry-symfony  4.1.4 

### Steps to Reproduce

1. Install `symfony/cache` 5.3.* (haven't checked other major/minor versions, but I expect the same behaviour in other supported versions) and `doctrine/dbal` 3.1.1
2. Configure a doctrine connection in `cache/packages/{env}/doctrine.php`:

```php
return static function (ContainerConfigurator $containerConfigurator): void {
    $containerConfigurator
        ->extension('doctrine', [
            'dbal' => [
                'default_connection' => 'mysql',
                'connections' => [
                    'mysql' => [
                        'driver' => 'pdo_mysql',
                        'host' => env('..'),
                        'dbname' => env('..'),
                        'user' => env('..'),
                        'password' => env('..'),
                        'server_version' => param('..'),
                        'mapping_types' => ['enum' => 'string'],
                    ],
                ]
            ]
        ]);
```

3. Configure a cache adapter in `cache/packages/{env}/cache.php`:
    
```php
return static function (ContainerConfigurator $containerConfigurator): void {
    $containerConfigurator->extension('framework', [
        'cache' => [
            'pools' => [
                'pdo' => [
                    'default_lifetime' => 86400,
                    'adapters' => [
                        [
                            'name' => 'cache.adapter.pdo',
                            'provider' => 'doctrine.dbal.mysql_connection',
                        ],
                    ],
                ],
           ]
      ]
]);
```

4. Configure Sentry in `cache/packages/{env}/sentry.php`:

```php
return static function (SentryConfig $configurator): void {
    $configurator
        ->dsn('..');

    $tracing = $configurator
        ->tracing()
            ->enabled(true);

    $tracing
        ->dbal()
            ->enabled(true)
            ->connections(['mysql']);
```

(This uses the new generated Config objects, but can be achieved with regular php or yaml config as well).

This results in:
- A Symfony DI-service: `doctrine.dbal.mysql_connection`
- Sentry [wraps](https://github.com/getsentry/sentry-symfony/blob/master/src/Tracing/Doctrine/DBAL/TracingDriverMiddleware.php#L37) the `Connection` of the driver of this mysql connection with the TracingDriver ([similar with Dbal v2](https://github.com/getsentry/sentry-symfony/blob/master/src/Tracing/Doctrine/DBAL/ConnectionConfigurator.php#L43))
- A PDO [Cache adapter](https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/Cache/Adapter/PdoAdapter.php) that using this mysql connection

### Expected Result

The cache adapter continues to work and Sentry is able to do its tracing on dbal queries.

### Actual Result

```
14:22:03 WARNING   [cache] Failed to save key "xxx" of type string: Creating the cache table is currently not implemented for PDO driver "Sentry\SentryBundle\Tracing\Doctrine\DBAL\TracingDriver".
```

Which is thrown here: https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/Cache/Adapter/PdoAdapter.php#L156

That method expects the driver to be one of Dbal's known drivers, but instead gets the TracingDriver (set at https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/Cache/Adapter/PdoAdapter.php#L477). 

Is this a known issue and/or something I can do to prevent this? If needed I can try to provide a reproducer project.

**Comment by Jean85** [comment] 2021-07-06 18:48
This is possibly a duplicate of #488

**Comment by Jeroeny** [comment] 2021-07-07 07:14
> This is possibly a duplicate of #488

The cause of the issue seems to be the same indeed (the fact that the `Driver` is wrapped in another class which isn't recognized). Though the solution that's being discussed there would likely not solve this part.

I wonder if the [SQLLogger](https://github.com/doctrine/dbal/blob/3.1.x/src/Logging/SQLLogger.php) could be used instead of the middleware/driver wrapper. It seems it's made for both logging and tracing/timing. It's set in the same [Configuration class](https://github.com/doctrine/dbal/blob/3.1.x/src/Configuration.php#L50) as the middleware.  And for example the Symfony profiler also uses this integration to measure the timings of queries: https://github.com/symfony/doctrine-bridge/blob/5.3/Logger/DbalLogger.php#L59.

**Comment by Jean85** [comment] 2021-07-07 08:31
@ste93cry WDYT? The wrapping method seems to create a lot of issues.

**Comment by ste93cry** [comment] 2021-07-07 18:17
>The wrapping method seems to create a lot of issues.

Unfortuntely 😢 But our approach to wrapping is something considered safe and ok to do, otherwise the middleware feature of Doctrine would not have been implemented...

>I wonder if the [SQLLogger](https://github.com/doctrine/dbal/blob/3.1.x/src/Logging/SQLLogger.php) could be used instead of the middleware/driver wrapper

As you found out, that was our first approach. However, our is more reliable in the measurement of the query time because the implementation is closer to the native driver. Moreover, some queries like the ones to start or commit a transaction are logged in the DBAL using an hardcoded string rather than passing the real query to the logger, and although it's a nitpick I prefer the precision of our approach in logging also these queries with 100% fidelity regardless of what could happen

>I'd be willing to submit a PR

I don't think it's worth it mainly because we would have to maintain two different implementations that at the end provide the same feature. I instead prefer to solve this upstream, where the real issue is. About this, I see that you already opened a PR there which is being reviewed, so I would say that there is nothing to do here

**Comment by Jean85** [comment] 2021-07-07 20:51
I would also add that adding the approach through the SQLLogger is basically blocked (or made a lot harder to implement) due to https://github.com/doctrine/DoctrineBundle/issues/1280

**Comment by Jean85** [comment] 2021-07-07 20:55
> But our approach to wrapping is something considered safe and ok to do, otherwise the middleware feature of Doctrine would not have been implemented...

Yes, I agree with this. Basically, using a plain `instanceof` onto the DBAL driver to check which kind of connection do you have will no longer be tenable with DBAL 3.0, with our manual wrapping we're just ahead of the curve. IMHO we could nudge other packages toward changing their approach with this reasoning.

**Comment by Jean85** [comment] 2021-07-08 05:36
Great news, this will be fixed upstream in https://github.com/symfony/symfony/pull/42011 !

**Comment by Jeroeny** [comment] 2021-07-08 08:27
@ste93cry Thanks for the insights. I first stumbled upon the v2 implementation using Reflection. But the v3 implementation using the new Middleware functionality indeed should be usable like this. That's also why I started the PR for `symfony/cache` :). 

I guess this issue can be closed (or wait until the Symfony PR is merged) ?

**Comment by ste93cry** [comment] 2021-07-08 11:06
Let's leave this open until the bugfix is released so that if people stumble upon this they hopefully don't create a duplicate issue 😀

**Comment by ste93cry** [comment] 2021-07-26 18:53
I'm closing this because the patched version of Symfony has finally been released 🥳

**Closed by ste93cry** 2021-07-26 18:53 UTC
