### ISSUE TITLE
Add the parameter for enable or disable listen of exception.

### ISSUE THREAD

**Issue by ZhukV** [getsentry/sentry-symfony#92] opened 2017-11-09 15:18 UTC
In many cases, we should not send the error on development node.

Maybe add the parameter for control enable or disable listen to the exception?

```
sentry:
    enable: "!%kernel.debug%"
```

**Comment by Jean85** [comment] 2017-11-09 15:50
That's not always true. Sentry has the possibility to store the environment of the errors, so it can be used in development (or staging or whatever) too.

To disable error reporting, you can either include the bundle only in the prod environment, or set the DSN in the config as null.

(this is a duplicate of #76 #46 #38, closing for this reason)

**Closed by Jean85** 2017-11-09 15:50 UTC

**Comment by aonamrata** [comment] 2018-11-01 17:58
This should have been added to sentry docs. I was looking to do this in raven for node js. setting the DNS to null works.

**Comment by Jean85** [comment] 2018-11-02 13:29
That is already stated in the readme: https://github.com/getsentry/sentry-symfony#step-3-configure-the-sdk
