### ISSUE TITLE
Sentry not working on specific domain

### ISSUE THREAD

**Issue by thentges** [getsentry/sentry-symfony#94] opened 2017-11-16 09:29 UTC
Hi,
I have two different servers running the same Symfony application, one is my developement/testing server, the second is the production server.
I installed sentry using the bundle following the instructions given in the documentation, but i'm only receiving errors from the test server, no errors seems to be sent from the production server. 

Months ago, sentry worked fine on the two domains, and we didn't change anything.

I tried to install Sentry via monolog too, but the problem persists : we only get errors from the testing server.
Does anyone have an idea what could be wrong ?

Thanks

**Comment by Jean85** [comment] 2017-11-16 09:32
Have you inspected the configuration for differences? Maybe you have different `error_reporting` settings?

**Comment by thentges** [comment] 2017-11-16 09:53
I only configured the bundle adding my dsn to the config.yml file on my two projects, not setting anything else should use default configuration, right ?

**Comment by Jean85** [comment] 2017-11-16 09:55
Yes, but you would have to check the server configuration. Also, do you have a reproducible way to trigger an error on both systems? Are you sure that both server can talk to the Sentry one without issues?

**Comment by thentges** [comment] 2017-11-16 09:59
Yes we have a kind of "hidden" error on the project, on the two servers, when I trigger it on my testing server i get the error on sentry, but not when I do it on the production server.

I though sentry was code based and no server configuration could change it, what part of my server configuration do you recommend me to check ?

thanks for your responses

**Comment by thentges** [comment] 2017-11-16 10:20
I just checked, php.ini error_reporting settings are the same on the two server, this isn't the source of my problem.

Isn't calling the Sentry reporting manually in a controller like you recommend send only the error implemented in this controller ? I would like all my errors by Sentry, without having to define every possible error manually..

**Comment by Jean85** [comment] 2017-11-16 11:16
Nope, I was just suggesting a way to reproduce the issue in a controlled way: write a controller that sends something to Sentry, to rule out any possible misconfiguration or issue on the Sentry's side.

**Comment by thentges** [comment] 2017-11-17 13:48
Okay, thanks for the hint.
As you said, I writed a controller to send a custom msg to Sentry : I tested it in local mode, it worked. I tested it on my development server, it worked. But, when I tested it on my production server it didn't work..

**Comment by Jean85** [comment] 2017-11-17 13:55
It seems clear to me that, apart from possible mistakes while deploying to your prod server, it's the server's (configuration) fault.

I'll close this since it's not a bug of this bundle, but feel free to reply further.

**Closed by Jean85** 2017-11-17 13:55 UTC

**Comment by thentges** [comment] 2017-11-17 14:02
Okay thanks ! So now it's clear that the problem is on my side and not Sentry/Raven's side ?
The deployment is OK, so it should be server's fault.

I'm using nginx, i'm going to check the differences between my configuration and the recommended configuration for nginx provided by the documentation ( https://docs.sentry.io/server/nginx/ )

I'll keep you tuned.

Thanks you !

**Comment by thentges** [comment] 2017-11-17 14:14
the only thing i can't understand is that my nginx config is the same on my development server and production server..

**Comment by thentges** [comment] 2017-11-17 14:49
Do you think installing the sentry server on my server via Docker could solve the problem or the problem will still persist ?
