### ISSUE TITLE
Deprecation warnings in 4.1.0

### ISSUE THREAD

**Issue by jokaorgua** [getsentry/sentry-symfony#483] opened 2021-04-19 12:31 UTC
### Environment

How do you use Sentry?
self-hosted

Which SDK and version?

sentry-symfony 4.1.0
symfony 5.2.6

### Steps to Reproduce

Symfony reports a couple of deprecation warnings

```
1x: The "Sentry\SentryBundle\Tracing\Doctrine\DBAL\TracingDriver" class implements "Doctrine\DBAL\Driver\ExceptionConverterDriver" that is deprecated.

  1x: The "Sentry\State\HubAdapter::captureMessage()" method will require a new "EventHint|null $hint" argument in the next major version of its interface "Sentry\State\HubInterface", not defining it is deprecated.

  1x: The "Sentry\State\HubAdapter::captureException()" method will require a new "EventHint|null $hint" argument in the next major version of its interface "Sentry\State\HubInterface", not defining it is deprecated.

  1x: The "Sentry\State\HubAdapter::captureLastError()" method will require a new "EventHint|null $hint" argument in the next major version of its interface "Sentry\State\HubInterface", not defining it is deprecated.

```

### Expected Result

no warnings

**Comment by Jean85** [comment] 2021-04-19 15:18
The last three deprecations are fixed in https://github.com/getsentry/sentry-php/pull/1206, and will be released in the next patch version of `sentry/sentry`.

The first one instead is tricky, and I'm not sure we can overcome it... DBAL is pretty entangled now.

**Comment by man-htsts** [comment] 2021-09-20 18:14
```
bin/console doctrine:migrations:list -q
2021-09-20T21:12:46+03:00 [info] User Deprecated: The "Sentry\SentryBundle\Tracing\Doctrine\DBAL\TracingDriver" class implements "Doctrine\DBAL\Driver\ExceptionConverterDriver" that is deprecated.

```
How to suppress this error message?

**Comment by Jean85** [comment] 2021-09-21 07:22
We're trying something more with #553, but it's possible that those deprecations will never go away since we have to support both DBAL v2 & v3 at the same time.

**Comment by man-htsts** [comment] 2021-09-21 14:16
But how can i suppress this message from output, when i call `bin/console doctrine:migrations:list`?
Is there any way to hide it from output?

**Comment by Jean85** [comment] 2021-09-21 15:14
That's due to Symfony, not us, you need to check their docs.

**Comment by man-htsts** [comment] 2021-09-21 17:00
I don't deeply understand how errors are handled, but i think that it's an error(notice) inside error handler, and that is why it is not handled by other error handlers and go to STD_ERR in console.

```
monolog:
    handlers:
        sentry:
            type: sentry
            level: !php/const Monolog\Logger::ERROR
            hub_id: Sentry\State\HubInterface
        php_info_filter:
            type: filter
            handler: php_info
            accepted_levels: ["info"]
            channels: ["php"]
            bubble: false
        php_info:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.php_info.log"
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event"]
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type: firephp
        #    level: info
        #chromephp:
        #    type: chromephp
        #    level: info
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]

```

**Comment by ste93cry** [comment] 2021-09-21 18:15
I bet it won't, but can you please try updating to `4.2.3` and see if it solves the problem?

**Comment by Jean85** [comment] 2021-09-22 06:52
> I don't deeply understand how errors are handled, but i think that it's an error(notice) inside error handler, and that is why it is not handled by other error handlers and go to STD_ERR in console.

It's a deprecation, so it's handled like that. Since Symfony 5.1+, there's a dedicated channel: https://github.com/symfony/recipes/blob/master/symfony/monolog-bundle/3.7/config/packages/prod/deprecations.yaml

**Comment by nspyke** [comment] 2021-10-19 05:42
> I bet it won't, but can you please try updating to `4.2.3` and see if it solves the problem?

Hi @ste93cry. Upgrading to 4.2.3 has removed the deprecation warning. I was on 4.2.2 previously.

**Comment by ste93cry** [comment] 2021-10-19 11:29
I think that the deprecation gone because you also upgraded the `doctrine/dbal` package to `3.x`, otherwise it doesn't make sense because we're still implementing the old interface

**Comment by iker-barriocanal** [comment] 2021-10-19 16:03
IIUC, the warnings should be gone in the latest `4.2.3` release, right? If yes, can we close the issue?

**Comment by ste93cry** [comment] 2021-10-20 18:48
I just checked some projects I work on and I definitely still see the deprecation about the `ExceptionConverterDriver` interface. Unfortunately, the issue is not that easy to solve because we have to implement all interfaces to avoid failures with `instanceof` checks 😞

**Comment by Tofandel** [comment] 2022-02-02 18:49
Still seing deprecations in 4.2.3
```txt
2022-02-02T18:39:03+00:00 [info] User Deprecated: Class "Sentry\SentryBundle\Tracing\Doctrine\DBAL\TracingDriverConnection" should implement method "Doctrine\DBAL\Driver\Connection::getNativeConnection(): resource|object".
2022-02-02T18:39:03+00:00 [info] User Deprecated: Class "Sentry\SentryBundle\Tracing\Doctrine\DBAL\TracingServerInfoAwareDriverConnection" should implement method "Doctrine\DBAL\Driver\Connection::getNativeConnection(): resource|object".
2022-02-02T18:39:03+00:00 [info] User Deprecated: The "Sentry\SentryBundle\Tracing\Doctrine\DBAL\TracingServerInfoAwareDriverConnection" class implements "Doctrine\DBAL\Driver\ServerInfoAwareConnection" that is deprecated The methods defined in this interface will be made part of the {@see Driver} interface in the next major release.
2022-02-02T18:39:03+00:00 [info] User Deprecated: Class "Sentry\SentryBundle\Tracing\Doctrine\DBAL\TracingServerInfoAwareDriverConnection" should implement method "Doctrine\DBAL\Driver\Connection::getNativeConnection(): resource|object".
```

**Comment by wimwinterberg** [comment] 2022-02-11 10:45
hi ~ I also encounter the deprecation messages on the console. What I found out was that when I enabled Sentry as a logger DebugHandlersListener of SF was called after Sentry ErrorHandler was initialized. Therefore the following code

```php
$handler = set_exception_handler('var_dump');
$this->earlyHandler = \is_array($handler) ? $handler[0] : null;
restore_exception_handler();
```
sees the Sentry ErrorHandler instead of the Symfony ErrorHandler, what then results in the Logger not properly being setup for the ErrorHandler (which is normally done in DebugHandlersListener ::configure), which then results in the default BufferingLogger to be used for the deprecation message which are outputted at the end.

As a fix for this I used Sentry logger using the old behaviour using monolog.type=service instead of sentry and the lazy loaded that services. This way DebugHandlersListener __constructor is caller before Sentry changes the error_handler.

```yml
monolog:
  handlers:
    sentry:
      type: service
      id: App\Sentry\MonologHandler
```

see: https://symfony.com/doc/current/service_container/lazy_services.html
```yml
  App\Sentry\MonologHandler:
    lazy: true
    public: true
    arguments:
      $hub: '@Sentry\State\HubInterface'
      $level: !php/const Monolog\Logger::ERROR
```

I hope this helps

**Comment by Jean85** [comment] 2022-02-14 08:01
Thanks @wimwinterberg but unfortunately this is a known issue; see #337.

**Comment by pkly** [comment] 2022-02-23 09:45
I'm having the same issue @Tofandel is having, also on symfony 5.4.2 / php8.1

**Comment by tacman** [comment] 2022-03-17 00:20
The deprecation warnings make it almost impossible to see real errors.
Odd, since this is Sentry's entire reason for being.

No idea how to solve it, alas, so I'm just part of the chorus hoping it
happens.

**Comment by ste93cry** [comment] 2022-03-17 00:39
>The deprecation warnings make it almost impossible to see real errors.

I don't think that this is a fair statement. Just one deprecation remains, which is the one related to the DBAL, and it would have been fixed already if it was so easy to do it. The reality is a bit different unfortunately: that class is deprecated, but we have to implement it because otherwise our decorator would break the applications that expect the connection to be an instance of `ExceptionConverterDriver`

**Comment by tacman** [comment] 2022-03-17 01:39
To be fair, I think that Symfony makes it too hard to hide
deprecation errors.   And monolog is very confusing to someone who just
wants to capture errors.

It's not just Sentry, of course, several older bundles are full of
deprecation warnings.  It's an oft-discussed issue.

**Comment by richardhj** [comment] 2022-03-19 09:14
For me, it's not just the deprecations (from #596) but my app effectively and suddenly (with Sentry v3.4?) stopped working.

<img width="732" alt="Screenshot 2022-03-19 at 10 10 27" src="https://user-images.githubusercontent.com/1284725/159115104-efff3272-43fe-4a4a-957d-fcb13428a02b.png">

**Comment by ste93cry** [comment] 2022-03-19 11:25
Please open a separate issue and post more details. An image of an error message is not enough to understand what's happening

**Comment by sladg** [comment] 2023-02-15 18:52
Hey! 
Facing same issue with deprecation error. Muting it in `phpunit` config does not work, using `SYMFONY_DEPRECATIONS_HELPER=weak` works fine, but that would result with any other deprecation slipping in our codebase and that's not wanted.

Can we fix this error? Some check on what version is used and determining correct class?

```
php -c [./php/conf.d/php.ini](https://bitbucket.org/usertech/fllite-be/src/02000d2c15d4d34752e214ed372108c260809179/php/conf.d/php.ini) vendor/bin/phpunit --configuration [./phpunit.xml](https://bitbucket.org/usertech/fllite-be/src/02000d2c15d4d34752e214ed372108c260809179/phpunit.xml) --testsuite unit
PHPUnit 9.5.20 #StandWithUkraine
Testing 
..............................                                    30 / 30 (100%)
Time: 00:00.032, Memory: 14.07 MB
OK (30 tests, 66 assertions)
Remaining indirect deprecation notices (2)
  2x: The "Sentry\SentryBundle\Tracing\Doctrine\DBAL\TracingDriverForV3" class implements "Doctrine\DBAL\VersionAwarePlatformDriver" that is deprecated All drivers will have to be aware of the server version in the next major release.
    2x in AirportCodeNormalizerTest::testNormalizeCustom from App\Tests\unit\Application\Airport
make: *** [test-unit] Error 1
```

Running following versions:
```
"doctrine/annotations": "^1.0",
"doctrine/doctrine-bundle": "^2.5",
"doctrine/doctrine-fixtures-bundle": "^3.4",
"doctrine/doctrine-migrations-bundle": "^3.2",
"doctrine/orm": "^2.11"

"sentry/sentry-symfony": "^4.2",

... symfony packages 5.4.* ...

```

**Comment by ste93cry** [comment] 2023-02-16 09:03
I would love to, but I don't think it's feasible without the proof that the majority of people upgraded from DBAL `2.x`. When we're talking about the userbase to support, the Sentry team is unwilling to leave a sizable chunk of users behind in most if not all of the cases, no matter the reason. @cleptric is now to the go-to person for this kind of decisions through

**Comment by cleptric** [comment] 2023-02-16 09:56
Looking at https://packagist.org/packages/doctrine/dbal/stats#major/all, I do see a 50/50 split between v2 and v3. So I don't see us of removing dbal v2 support anytime soon.

**Closed** 2024-12-10 14:33 UTC
