### ISSUE TITLE
kernel.exception doesn't work with sentry

### ISSUE THREAD

**Issue by medliii** [getsentry/sentry-symfony#130] opened 2018-05-14 11:49 UTC
Hi.
Symfony developers wrote that it's bundle bug 
https://github.com/symfony/symfony/issues/27253

There are 3 continious steps:
1) 
![image](https://user-images.githubusercontent.com/1991105/39983961-33e2eeac-5762-11e8-98bc-ef5dd46bd3e1.png)
2) 
![image](https://user-images.githubusercontent.com/1991105/39984012-5faf118c-5762-11e8-9616-2a1869fe460a.png)
3) 
![image](https://user-images.githubusercontent.com/1991105/39984018-674b185a-5762-11e8-81d2-96a6af0a08b8.png)

Bug on 3d screenshot.
So this code never triggered

`$this->exceptionHandler = function (\Exception $e) use ($kernel, $request, &$hasRun) {
                        if ($hasRun) {
                            throw $e;
                        }
                        $hasRun = true;
                        $kernel->terminateWithException($e, $request);
                    };`

**Comment by Jean85** [comment] 2018-05-14 12:45
Hi. I've responded in the original Symfony issue; could you please report which versions of Symfony, the bundle and the Sentry SDK are you using? What is the reproducible steps that you have to have this bug?

**Comment by Jean85** [comment] 2018-05-29 09:21
Quoting @ragusa87 from getsentry/sentry-php#605:

> It's common to load the symfony-bundle in every environment and set the DSN only for production (in config_prod.yml), in this case, errors are not send to sentry due to an empty DSN but the deprecated messages are gone as the raven handler are registered. At least I have seen this config in many projects.

No that is not the correct way of installing this bundle. You shouldn't enable it everywhere, but just in the right environments! In fact, [the readme advises otherwise], suggesting a conditional enabling:

```php
    if (in_array($this->getEnvironment(), ['staging', 'prod'], true)) {
        $bundles[] = new Sentry\SentryBundle\SentryBundle();
    }
```

With that snippet, you'll be covered!
Closing this since we found the right approach to avoid this issue.

**Closed by Jean85** 2018-05-29 09:21 UTC

**Comment by ragusa87** [comment] 2018-05-29 12:47
@Jean85 Thanks for your message I will do that in the meantime.

PS: Having a Symfony "staging" environment like in you sample is in my opinion a bad practice. Your staging should react as you production server, so I always use the Symfony "prod" environment in both case and deploy another parameters.yml between prod and staging servers (or use %env()% variables). Anyway it's just a personal opinion ;)

**Comment by Jean85** [comment] 2018-05-29 15:43
Oh yeah I agree totally, I just use the different environment to pilot that exact thing... my `config_staging.yml` is just:

```yaml
imports:
    - { resource: config_prod.yml }
```
