### ISSUE TITLE
The bundle v4 logs deprecated warnings

### ISSUE THREAD

**Issue by alex-pravdin-sn** [getsentry/sentry-symfony#505] opened 2021-05-17 03:35 UTC
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
sentry-symfony package v4.1.1

### Steps to Reproduce

I have the following Sentry configuration in my app where I want to log to Sentry errors only:
```
sentry:
  register_error_listener: false # Disables the ErrorListener to work thru the Monolog handler
  dsn: '%sentry_dsn%'
  messenger:
    enabled: true # flushes Sentry messages at the end of each message handling
    capture_soft_fails: true # captures exceptions marked for retry too
  options:
    environment: '%kernel.environment%'
    integrations:
      - 'Sentry\Integration\IgnoreErrorsIntegration'

monolog:
  handlers:
    sentry:
      type: sentry
      level: !php/const Monolog\Logger::ERROR
      hub_id: Sentry\State\HubInterface

services:
  _defaults: # Defaults for THIS file only
    autowire: true
    autoconfigure: true
    public: false

  Monolog\Processor\PsrLogMessageProcessor:
    tags: { name: monolog.processor, handler: sentry }

  Sentry\Integration\IgnoreErrorsIntegration:
    arguments:
      $options:
        ignore_exceptions: #exclude validation errors
          - Symfony\Component\Security\Core\Exception\AccessDeniedException

  Symfony\Bridge\PsrHttpMessage\Factory\PsrHttpFactory:

  Symfony\Bridge\PsrHttpMessage\HttpMessageFactoryInterface: '@Symfony\Bridge\PsrHttpMessage\Factory\PsrHttpFactory'

  Http\Factory\Guzzle\ServerRequestFactory:

  Psr\Http\Message\ServerRequestFactoryInterface: '@Http\Factory\Guzzle\ServerRequestFactory'

  Http\Factory\Guzzle\UploadedFileFactory:

  Psr\Http\Message\UploadedFileFactoryInterface: '@Http\Factory\Guzzle\UploadedFileFactory'

  Http\Factory\Guzzle\ResponseFactory:

  Psr\Http\Message\ResponseFactoryInterface: '@Http\Factory\Guzzle\ResponseFactory'

  Http\Factory\Guzzle\StreamFactory:

  Psr\Http\Message\StreamFactoryInterface: '@Http\Factory\Guzzle\StreamFactory'

```

### Expected Result

Only errors logged.

### Actual Result

I see a lot of `deptecated` and `notice` errors like these:

![image](https://user-images.githubusercontent.com/61450549/118429186-12554200-b70c-11eb-8636-10047b0b3bf4.png)

![image](https://user-images.githubusercontent.com/61450549/118429222-25681200-b70c-11eb-9a0b-d2c5cbb02366.png)

What I'm doing wrong?

**Comment by Jean85** [comment] 2021-05-17 09:54
Do you have other Monolog handlers configured? Those work in cascade, that may be the culprit.

**Comment by alex-pravdin-sn** [comment] 2021-05-17 10:00
Here is the other monolog handler config:

```
monolog:
  handlers:
    console:
      type: console
      channels: [ "!event", "!doctrine", "!console" ]
      process_psr_3_messages: true
```

**Comment by Jean85** [comment] 2021-05-17 13:57
Oh, but I just noticed! You're using the Monolog's handler, the one provided by MonologBundle, not ours!

To use ours, you'll need this service definition:

```yaml
services:
    Sentry\Monolog\Handler:
        arguments:
            $hub: '@Sentry\State\HubInterface'
            $level: !php/const Monolog\Logger::ERROR
            $bubble: false
```

**Comment by alex-pravdin-sn** [comment] 2021-05-17 23:39
But the documentation https://docs.sentry.io/platforms/php/guides/symfony/ says to use this method only if using `symfony/monolog-bundle` version prior to 3.7. In my case, this 3.7 version is used, so I configured the monolog handler according to the documentation.

**Comment by Jean85** [comment] 2021-05-18 13:26
@ste93cry IIRC you changed that piece of documentation, right? Can you chime in?

**Comment by ste93cry** [comment] 2021-05-18 21:41
Documentation is correct, if `symfony/monolog-bundle >=3.7` is used there is the support to set a custom Sentry hub which can be linked to `Sentry\State\HubInterface` and therefore it's the suggested way to use Monolog because you don't have to care about registering the handler itself. Before that version instead, the handler that was instantiated by the bundle was creating a completely new instance of the hub on the dependency container and was not setting it as active, therefore all integrations and the client itself was not binded to it.

Btw, our handler is not doing anything special, it simply extends the [`AbstractHandler`](https://github.com/Seldaek/monolog/blob/bac1ddd01913a073f236b5d0aa27cb2ef3b37b6a/src/Monolog/Handler/AbstractHandler.php) class which should filter out all messages whose level is below the given threshold. I don't understand why it doesn't work for you, but I'm not sure this is something depending on us...

P.S. if you install the `symfony/psr-http-message-bridge` package (and related recipe) there should be no need to register all those PSR services

**Comment by ste93cry** [comment] 2021-07-07 17:08
I'm closing this issue because it's quite old, and there are no updates so I assume either the problem is solved or you don't need anymore assistance

**Closed by ste93cry** 2021-07-07 17:08 UTC
Labels: Type: Question
