### ISSUE TITLE
Use less memory

### ISSUE THREAD

**Issue by iaicam** [getsentry/sentry-symfony#437] opened 2021-02-06 21:07 UTC
This bundle literally adds hundreds of MB of memory usage to my behat suite.

Before 64MB
After: 254MB.

It would be nice to not require an extra 190mb of ram for a bundle that shouldn't even be used in test mode. I've tried to isolate it into just being loaded in prod mode and it's the same issue.

**Comment by ste93cry** [comment] 2021-02-06 21:11
This bundle is quite simple as it simply integrates the core SDK with Symfony, so I hardly think that it's the cause of the memory increase. It may be an issue in the core SDK, but noone ever reported this before. Are you able to track down the piece of code that is usingso much memory?

**Comment by iaicam** [comment] 2021-02-07 08:03
No, I am not able to. All I can tell you is my steps to reproduce are run Behat and look at the memory usage. Then do require the bundle via composer/flex accept the recipe and run Behat again. This is the second project where adding the bundle resulted in the memory usage spiking I noticed because it resulted in my builds failing due not having enough memory. I remove the bundle and the memory goes back to normal.  My efforts have only been so far to try and make sentry only load in prod mode, config only in prod and bundle only in prod and still the result is the same. 

My only idea is a leak in the intercepting logging? I have no idea, it seemed completely nuts to me too.

**Comment by Jean85** [comment] 2021-02-08 15:34
IMHO the only possibility is that you're generating a lot of notices/warnings that are being captured by the bundle but never sent, hence laying in the buffer to be sent.

Do you have the DSN enabled in all your environments? Can you try to change the error level at which you let Sentry intervene? Do you use any logging integration? (yes, logging, especially with the crossed-finger approach could lead to memory exaustion)

**Comment by iaicam** [comment] 2021-02-08 16:26
Notice/warnings would have failed the behat tests. 

> Can you try to change the error level at which you let Sentry intervene?

No, after the database issue, I decided to go with Rollbar. This was meant to help me find issues, not cause issues.

>  Do you use any logging integration? (yes, logging, especially with the crossed-finger approach could lead to memory exhaustion)

Yes, I have pretty much a default monolog configuration.

**Comment by Jean85** [comment] 2021-02-08 16:36
> Notice/warnings would have failed the behat tests.

Not necessarily, especially if the root cause could be into the error handler.

Main culprits IMHO should be that or the transport, which is set depending on what you have installed.

Sorry for not being much more helpful, but it's hard to troubleshoot without more details on your end.

**Comment by ste93cry** [comment] 2021-02-08 20:57
>No, after the database issue, I decided to go with Rollbar. This was meant to help me find issues, not cause issues.

As I already said in the other issue you opened, I'm not sure I understand how we are meant to help you if you open an issue, don't provide any reproducible case (script, repo, whatever) and simply say that the bundle uses a lot of memory. Be aware, I'm not negating the problem, but if the answer to the request of more information or help in finding the root cause is "I switched to another product", then I don't understand why you opened this issue expecting support from us  in the first place. Anyway, I just did a really simple test:

```sh
$ composer create-project symfony/skeleton
$ composer require behat/behat
$ vendor/bin/behat --init
$ vendor/bin/behat

No scenarios
No steps
0m0.36s (8.67Mb)

$ composer require sentry/sentry-symfony
$ vendor/bin/behat

No scenarios
No steps
0m0.35s (9.25Mb)
```

It doesn't look like the memory usage is so big, but of course I have no tests to execute. If you aren't able to came up with a reproducible test case, I think there is very little we can do on our side to help you more than what we already tried to do

**Comment by iaicam** [comment] 2021-02-09 13:47
> but if the answer to the request of more information or help in finding the root cause is "I switched to another product", then I don't understand why you opened this issue expecting support from us in the first place. 

The answer to can I do it, is no because I switched. And I am not expecting support from either of you. I was expecting support from the for-profit company that I was in the onboarding process to give them money. Also, the reason I created the issue is to be helpful and tell sentry they have an issue so they can solve it. They can't solve the issue if they don't know about it. But since they're not supporting this project even though it is their project and they got 66.5 Million in funding I can see why they haven't fixed it because they won't know about it. As you can tell, I'm rather annoyed that the company hasn't responded at all to this. Sorry if it feels like I am taking it out on you, you're just trying to be helpful to the community.

> It doesn't look like the memory usage is so big, but of course I have no tests to execute. If you aren't able to came up with a reproducible test case, I think there is very little we can do on our side to help you more than what we already tried to do

That's a 10% increase on a hello world project. It's doing nothing yet 10% increase. That looks like a warning sign to me. If I was going to investigate this without the code base that caused it, I would use an open-source Symfony app. Maybe Slyius instead of a skeleton. But you're skeleton example to me shows there is an issue. 10% increase while doing nothing is extremely odd.

**Comment by Jean85** [comment] 2021-02-09 14:25
10%? It's 0.58Mb of RAM, probably due to the fact that he's increasing the Composer dependency tree (and the DI container) by nearly 50%

I personally have 3 different Symfony project in production right now (unfortunately with the previous major versions for now), and all 3 of them work without a lot of memory, IIRC >40-50Mb. You have a complex setup and having this bundle added is triggering something strange, I concur; but we need more informations to understand where the issue is.

I would suggest a Blackfire profile to understand where the memory bloat is occurring, we could at the very least pinpoint to a specific piece of code in this way.

**Comment by iaicam** [comment] 2021-02-09 15:29
> You have a complex setup and having this bundle added is triggering something strange, I concur; but we need more informations to understand where the issue is.

This is the thing and why there is no real info to give. My setup is basically standard the only advance config setup I have is I have two dbal connections. Other than that, it's basically default. I've not even got to the point where I need to customise configs. It's basically a web app that has logic and a bunch of tests.

**Comment by Jean85** [comment] 2021-02-10 10:48
It's not just configs, it's also what components and dependencies are you using. 
Bare example, you use Behat and I don't. 
As you said in #436, you use TimescaleDB with a Postgre driver, that's not common at all.

There are too many variables at play. As I've already said, you can try to narrow our search with a comparison of 2 Blackfire profiles, one with the bundle and one without, even locally would be fine; since you're seeing a huge spike in memory usage, that profile should be able to highlight pretty fast where that memory is being spent.

**Comment by ste93cry** [comment] 2021-02-20 19:45
I'm closing this because there are not enough information to go on, and because I don't feel we can do much without pinpointing to a particular issue. Feel free to reopen should you have more details

**Closed by ste93cry** 2021-02-20 19:45 UTC
Labels: Status: Needs Information
