### ISSUE TITLE
trigger_error not reporting

### ISSUE THREAD

**Issue by Mika56** [getsentry/sentry-symfony#267] opened 2019-10-29 14:48 UTC
Hi,

We're currently deprecating some of our actions.
I've added the following code to these actions:
```php
@trigger_error(__METHOD__.' has been deprecated', E_USER_DEPRECATED);
```
I can't understand why, but Sentry won't report these errors, so I've added:
```php
$this->sentry->captureLastError();
```

It works, but for some reason a lot of information is not reported, including the request's URL.

What is the official way to report deprecations? I don't want to use an `Exception` because the action needs to still work.
The bundle's configuration is pretty standard:
```yml
sentry:
    dsn: "%sentry_dsn%"
    options:
        capture_silenced_errors: true # tried adding this, did not change a thing
        default_integrations: true # tried adding this, did not change a thing
        error_types: 'E_ALL' # tried adding this, did not change a thing
        send_default_pii: true
```

**Comment by Jean85** [comment] 2019-10-30 10:31
This is very strange, `capture_silenced_errors: true` and `error_types: 'E_ALL'` should do the trick. Are you sure that your Sentry intergration is working? Did you receive other error reports?

**Comment by Mika56** [comment] 2019-11-05 13:13
The Sentry integration seems to be working fine, if I add `throw new \Exception()` it correctly reports everything

**Comment by Jean85** [comment] 2019-11-05 16:47
What happens if you trigger an unsilenced error, like
```php
trigger_error('Test', E_USER_DEPRECATED);
```
or

```php
trigger_error('Test', E_USER_WARNING);
```

?

**Comment by Mika56** [comment] 2019-11-06 14:47
To be certain that this is not my project that catches the error before Sentry can report them, I've created a new project:
```
$ composer create-project symfony/framework-standard-edition test-sentry "3.4.*"
(...)
# Change config.platform.php to 7.2 in composer.json
$ composer require sentry/sentry-symfony:^3.0
# Update app/AppKernel.php and app/config/config.yml (sentry.dsn and sentry.options.error_types: 'E_ALL')
# Add trigger_error('Test', E_USER_DEPRECATED') to src/AppBundle/Controller/DefaultController.php
```
I've tried with E_USER_DEPRECATED, E_USER_WARNING, silenced or not, and in dev and prod, and never got anything sent to Sentry.
If I `throw new \Exception('Test exception');`, it gets reported correctly, so integration is working

**Comment by Jean85** [comment] 2019-11-06 20:36
I did follow your instructions and the event got to Sentry at the first try. The issue seems to be on your setup, probably on your php.ini settings.

**Comment by Mika56** [comment] 2019-11-07 08:18
That seems odd, I'm running a standard PHP7.2 from Sury (with XDebug). Would you mind sharing your phpinfo() so I can compare?

**Comment by Jean85** [comment] 2019-11-07 10:55
Here's the output of `php -i`: [php-i.zip](https://github.com/getsentry/sentry-symfony/files/3819193/php-i.zip)

I've just removed the info about env variables. Closing as this is not a reproducible bug.

**Closed by Jean85** 2019-11-07 10:55 UTC
Labels: support

**Comment by jordipolo87** [comment] 2020-07-19 18:41
Hello @Jean85 I'm having the same issue, have you finally resolve it?
