### ISSUE TITLE
Performance monitoring?

### ISSUE THREAD

**Issue by ldath** [getsentry/sentry-symfony#388] opened 2020-11-17 18:02 UTC
If it is possible with current version to use Performance Monitoring can we have example with the `traces_sampler`?

I'd like to sent transactions but discard health endpoint transactions. 

If it is not possible to use Performance monitoring with the current version then when this will be possible?

**Comment by W0rma** [comment] 2020-11-17 18:13
Probably duplicate of https://github.com/getsentry/sentry-symfony/issues/382, https://github.com/getsentry/sentry-symfony/issues/380 and https://github.com/getsentry/sentry-symfony/issues/374

**Comment by ldath** [comment] 2020-11-17 22:03
`traces_sampler` gives you the opportunity to choose dynamically `traces_sample_rate` based on the transaction data. This is a new feature described here: https://docs.sentry.io/platforms/php/performance/#sample-specific-transactions 

Adding new version 3.x of the Sentry SDK, in my opinion, will not be enough as we need to somehow set this in the `sentry.yaml` 
 which is managed by the Bundle. 

Also will be nice to have this documented with an example of how.

**Comment by stayallive** [comment] 2020-11-18 08:51
Yes `3.x` is not everything but is needed as the first step, and with `3.x` the new `traces_*` options will become available. The PR for this is here: #385, it was merged yesterday so a release will be underway but it's possible there is still a bit of work to be done before a release will be made.

A little more patience!

**Comment by Jean85** [comment] 2020-11-18 10:05
> Probably duplicate of #382, #380 and #374

Yes, absolutely. Keep a look onto the 4.0 milestone.

**Closed by Jean85** 2020-11-18 10:05 UTC
Labels: Type: Question

**Comment by ldath** [comment] 2020-11-18 10:12
> Yes `3.x` is not everything but is needed as the first step, and with `3.x` the new `traces_*` options will become available. The PR for this is here: #385, it was merged yesterday so a release will be underway but it's possible there is still a bit of work to be done before a release will be made.
> 
> A little more patience!

No problem :) - I can wait - at least in the Python Flask I have this done and already this new sentry feature is useful for me and was worth changing from the free plan  👍.
