### ISSUE TITLE
Cache tracing support cannot be enabled

### ISSUE THREAD

**Issue by VincentLanglet** [getsentry/sentry-symfony#508] opened 2021-05-19 08:25 UTC
### Environment

I have `"symfony/cache": "4.4.*"` in my composer.json but still get the error message
``` 
Cache tracing support cannot be enabled because the symfony/cache Composer package is not installed.
```

This occurs since the PR of @ste93cry  https://github.com/getsentry/sentry-symfony/pull/487

4.1.0 works fine but 4.1.1 doesn't. Any idea why ?

**Comment by ste93cry** [comment] 2021-05-19 08:27
Duplicate of #500

**Closed by ste93cry** 2021-05-19 08:27 UTC

**Comment by VincentLanglet** [comment] 2021-05-19 08:40
Didn't see it was already solved.
Would it be possible to make a new release ? :)

**Comment by ste93cry** [comment] 2021-05-19 08:44
Yes, I tried yesterday but there are some issues with the bot that does the release and I'm waiting for the Sentry guys to help me sort the issue out 😉

**Comment by ste93cry** [comment] 2021-05-19 11:23
Version `4.1.2` that includes the fix has been released 👍
