### ISSUE TITLE
performance monitoring not working

### ISSUE THREAD

**Issue by tobikars** [getsentry/sentry-symfony#382] opened 2020-10-27 09:26 UTC
When I set traces_sample_rate: 1.0, this is not supported. 

This means no performance data is collected (and the sentry-feature is disabled in the portal)

Is there a way we can upgrade from 2.2 to >3.5

If this cannot be supported, where can I add the traces_sampler function?

**Comment by Jean85** [comment] 2020-10-27 14:25
Closing as duplicate of #380, see #374

**Closed by Jean85** 2020-10-27 14:25 UTC
