### ISSUE TITLE
Causes too many database connections via behat.

### ISSUE THREAD

**Issue by iaicam** [getsentry/sentry-symfony#436] opened 2021-02-06 20:56 UTC
### Environment

How do you use Sentry?
Sentry SaaS 

Which SDK and version?
3.10 SDK
bundle 4.0.1

### Steps to Reproduce

1. `composer require sentry/sentry-symfony`
2. Accept recipe
3. add in the following sentry config 
```
sentry:
    dsn: '%env(SENTRY_DSN)%'
    options:
        environment: '%kernel.environment%'
        integrations:
            - 'Sentry\Integration\IgnoreErrorsIntegration'
services:

    Sentry\Integration\IgnoreErrorsIntegration:
        arguments:
            $options:
                ignore_exceptions:
                    - Symfony\Component\HttpKernel\Exception\NotFoundHttpException
                    - Symfony\Component\Security\Core\Exception\AccessDeniedException
                    - Symfony\Component\Security\Core\Exception\AuthenticationCredentialsNotFoundException
```
4. Commit and push to bitbucket
5. Bitbucket pipeline runs.
6. 
### Expected Result

Behat passes normally

### Actual Result

Behat fails half way through with every test resulting in the same error

```
  ╳  PDOException: SQLSTATE[08006] [7] FATAL:  sorry, too many clients already in vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38
  ```
### Note

It may be useful to know I have two dbal connections one for MySQL and one for TimescaleDB which uses the postgres driver and it's the timescaledb that is failing.

**Comment by iaicam** [comment] 2021-02-06 21:07
This also happens on 3.5.8.

**Comment by Jean85** [comment] 2021-02-08 15:31
The issue seems to be raised from PDO itself, since `PDOConnection.php:38` is a call to `parent::__construct`. Doesn't seem to me something related to Sentry, but maybe only triggered by its installation.

Maybe you have some connection limitation in your DB?

**Comment by iaicam** [comment] 2021-02-08 15:40
The connection issue will come from Postgres/Timescale. However, it is only caused when I installed the sentry bundle. Literally, the only change made was enabling the sentry bundle and the error arrived and when I removed it the error left. It seems logical that somehow the sentry bundle is interacting with Doctrine/Dbal/PDO in a way that causes it to lose a connection and regenerate a new one.

**Comment by Jean85** [comment] 2021-02-08 15:50
That's not the only possible interaction; adding a new bundle could heavily shape how the DI container is dumped, hence creating the possibility for a trigger (but not a direct cause) of this issue.

Citing a fast search: https://www.enterprisedb.com/blog/postgresql-pgpool-connection-pool-database-load

> Simply put, this error appears when the number of clients connected to the database exceeds the concurrent limit max_connections defined in the postgresql.conf file.

So, you're connecting too many times. Are you sure that your container is not over-instantiating its client multiple times? Or not sharing the instances?

**Comment by iaicam** [comment] 2021-02-08 16:19
> That's not the only possible interaction; adding a new bundle could heavily shape how the DI container is dumped, hence creating the possibility for a trigger (but not a direct cause) of this issue.

No that is the only interaction. Well, I did have to raise the PHP memory limit because of the memory usage caused by this bundle. Oh, and I had to manually add a dependency this bundle has. Overall, I tried to use this bundle and encountered 3 separate issues. The bug report is legit. I understand why you firmly believe this bundle is not the cause because it's completely nuts but sadly it is.

![image](https://user-images.githubusercontent.com/47746941/107247614-beaeca80-6a31-11eb-9f9f-261ed1777072.png)

**Comment by Jean85** [comment] 2021-02-08 16:42
I'm saying that the bundle is not the root cause, but I agree that it's triggering the issue. I'm convinced that it's not the root cause since our code has no other way to interact with a database connection, so it's something a lot more complex that "your bundle has a bug". You can understand my scepticism since this is a very strange bug report, and this bundle is widely used, with no reports of such memory bloats up until now.

Please keep in mind that this is an open source library and we're volunteers, not paid employees. And without further details on your end, we're unable to help further.

**Comment by iaicam** [comment] 2021-02-08 19:30
> Please keep in mind that this is an open source library and we're volunteers, not paid employees. And without further details on your end, we're unable to help further.

I was about to ask. If this bundle is actually supported by Sentry since the responses have been coming from developers other than them. Since this is an official bundle, I was under the impression that it is part of the service they're selling. This is meant for the company and not you guys, but I find it really bad that Sentry is relying on unpaid help for their customer support. Which this basically is.

**Comment by ste93cry** [comment] 2021-02-08 20:13
Noone ever reported this issue before. This is not to say there is no bug, there may very well be one (here or in the main SDK), but without further information it's simply impossible to track down the issue, and given that the issue is involving at least one element that is not reproducible without a test case (e.g. a repo with a project that reproduces the issue), I don't understand how you expect us (or the Sentry folks, in case) to help you further

>I had to manually add a dependency this bundle has

I'm pretty sure you're issue is the same as #379, which is not a fault of this bundle but rather an unfortunate consequence of having installed the `SensioFrameworkExtraBundle` bundle which expects the `nyholm/psr7` package to be installed without requiring it in its `composer.json` when the `HttpFoundationFactoryInterface` interface exists. This problem causes applications to break as soon as something else requires `symfony/psr-http-message-bridge`, which is the package providing that interface, and it's gonna be solved in version `6.0` of that bundle.

>I find it really bad that Sentry is relying on unpaid help for their customer support

Note: I'm talking as a contributor, so these are my thoughts. Paid support can be contacted on the Sentry website, if you need it. I don't think GitHub is the right place to expect this kind of support, but rather a place where to discuss about bugs and maybe contribute back to the project.

**Comment by iaicam** [comment] 2021-02-09 12:19
I'll add my doctrine.yaml to help you guys.

```yaml
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
            timescale:
                url: '%env(resolve:TIMESCALE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        connection: default
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        resolve_target_entities:
            HumblyArrogant\Underpin\User\Entity\UserInterface: App\Entity\User
            HumblyArrogant\Underpin\User\Entity\TeamInterface: App\Entity\Team
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
            Underpin_User:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/vendor/humblyarrogant/underpin-bundle/src/User/Entity'
                prefix: 'HumblyArrogant\Underpin\User\Entity'
                alias: Underpin_User
            Underpin_BackOffice:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/vendor/humblyarrogant/underpin-bundle/src/BackOffice/Entity'
                prefix: 'HumblyArrogant\Underpin\BackOffice\Entity'
                alias: Underpin_BackOffice
```

The customer entities from the bundles only use MySQL so won't use the pgsql driver which is failing.

> Note: I'm talking as a contributor, so these are my thoughts. Paid support can be contacted on the Sentry website, if you need it. I don't think GitHub is the right place to expect this kind of support, but rather a place where to discuss about bugs and maybe contribute back to the project.

This is an **official** and therefore supported the project of a company that I **was going to pay money** to. It is required as part of the **onboarding** process. It does not seem unreasonable to expect at least on employee to swing by on an onboarding error.  This is basically part of the person's first experience with Sentry a **for-profit company** and if the experience is that they will have to rely on the kindness of strangers to help them onboard to a company that they will be paying money to, it's not good. First impressions matter. If this was an unofficial bundle, it would be completely different, but this is not. I even checked the license to see if it was copyrighted to other people but it's copyrighted to a for-profit company. This is a technical product and **requires technical onboarding**, therefore, technical support and sales will come via its GitHub support system. This is software from a for-profit company. So I feel like the whole you can pay for support when I was literally going to pay them and I was doing the onboarding trial, is just as bad as Sentry not having a single paid employee comment on this. Especially since the CTO @dcramer has visited this thread. **Literally, the CTO has swung by and didn't say anything or provide any support. As I said, this is basically customer support you're doing for free, for a for-profit company.**

**Comment by Jean85** [comment] 2021-02-09 14:26
@iaicam please keep the tone civil; as we've already said it, if you want the for-profit company's support, it's there, on their site. A Github issue is never the correct way to ask for support, if not specified otherwise. As OSS maintainers, we just try to be helpful since we're most knowledgable on the subject, but if you require immediate assistence, support@sentry.io is the way to go.

I understand that you're requiring help, but you're asking for it on the wrong place then.

PS: how do you know if David has swung by? I didn't see any comments from him anywhere on the PHP repos since months, maybe years.

**Comment by iaicam** [comment] 2021-02-09 14:49
> @iaicam please keep the tone civil;

The tone is civil. I haven't been abusive or disrespectful. I've merely stated truths that you don't like. And I'm attacking a company and not you other people who are providing free customer support on the behalf of Functional Software inc (Sentry). Welcome to customer support, customers will be brutally honest and not sugar coat things. Its business. Sadly you're not getting paid for it. If you onboard to any other product you would not expect some helpful stranger to be the one providing the technical support nor the code. The fact you don't realise that this is part of their onboarding process and part of their product and part of their customer support is why I keep replying.

> As OSS maintainers, we just try to be helpful since we're most knowledgable on the subject, but if you require immediate assistence, support@sentry.io is the way to go.

Yea, this is what I'm raking Functional Software inc over the coals for the lack of a single person in their employment taking care of a part of their product.

> I understand that you're requiring help, but you're asking for it on the wrong place then.

As previously pointed out, this is an official bundle that is required to use the product. A company should have support here as to onboard to their product, this is where the support requests come. If you disagree with either that Functional Software inc is a for-profit company, that Sentry's product requires technical integration, or that the integration is part of the product onboarding. Please explain why. I am at a lost. I try to use their pay for SaaS product and code and technical support is provided by someone else while being under their name. This is why this isn't just an OSS project with OOS support expectations, when a company takes money support is a valid expectation, especially on their offical github repository. I wouldn't be soo pissy at the company if they didn't leave you two hanging like this.

> PS: how do you know if David has swung by? I didn't see any comments from him anywhere on the PHP repos since months, maybe years.

1) A Twitter thread where he mentioned this bundle. 
2) And the fact he hearted a previous comment. 

This is a though customer support complaint on a companies communication channel and you as being left to handle it without support from the for-profit company belongs to. The company will literally brag about how they communicate with customers via GitHub and other channels, yet leave you hanging to deal with this while you think it's not. 

Honestly, I feel this subject is not useful to the actual issue at hand which is this bundle somehow drops the database connection without closing causing too many connections.

**Comment by Jean85** [comment] 2021-02-09 15:06
No, I don't feel personally attacked by "thruths". I feel personally attacked when you say something like 

> this bundle somehow drops the database connection without closing causing too many connections.

You're implying that the issue lies in this bundle that, since it's largely written by me, I know very well, and that's because I'm says that the cause is probably indirect and due to your project setup and/or the error handler, which isn't even on this repo, but on a related one.

Meanwhile, you're still dismissing:
 * the requests for further details and/or investigations to pinpoint the issue
 * the requests to ask for commercial support on the proper avenues
 * the remarks made by @dcramer and me (I found the [Twitter thread](https://twitter.com/that_guy_iain/status/1358861305206235138?s=21) just now), that underlines the fact that this GitHub repo is for the OSS part of it

If you want to have a paid-level of support, you shouldn't insist on asking for it here. If you insist on asking for it here, you're stuck with me and a best-effort response.

And in any case, you have to provide us with more details, or me nor the paid support we'll be never able to solve it.

I'll no longer reply if not provided with more technical details.

**Comment by chadwhitacre** [comment] 2021-02-09 15:43
> we're volunteers, not paid employees

Greetings, friends, paid employee here. 👋 I'm on the Open Source team, which means I have no idea about the PHP details, but I'm happy to help route this to the right place.

@iaicam Sorry for the frustration, you're right that you're in an officially supported Sentry repo, and three days is a long time to go without a proper response. We're grateful to @Jean85 @ste93cry and our other contributors, but ultimately yes it's Sentry's responsibility to stay on top of this repo. Sorry for not doing better with that, we are actively working to improve our open-source triage processes to keep up with our growth as a company and will continue striving to do better.

I'm checking with some folks internally to make sure this is routed to the right team, please stand by ...

**Comment by chadwhitacre** [comment] 2021-02-09 16:13
> Honestly, I feel this subject is not useful to the actual issue at hand

Agreed. I've (started a public repo to track meta issues with Sentry's open-source processes, and) reticketed the process discussion as https://github.com/getsentry/open-source-meta/issues/1. Let's move the conversation about support expectations over there. I'm going to go through this thread and "hide" as "off-topic" the parts that aren't relevant to the issue at hand so that we can focus better here. Thanks all for your understanding.

**Comment by mitsuhiko** [comment] 2021-02-09 17:23
@Jean85 gracefully donates a lot of his time into contributing to this library and I find the tone of the conversation here to be unnecessarily confrontational towards him.

His comments on the nature of the issue I believe are entirely correct and I'm not sure there is anything actionable here. I'm inclined to close this issue and direct you towards the support in the app. There the issue will be triaged by the support team and escalated accordingly.

**Comment by ste93cry** [comment] 2021-02-20 19:47
I'm closing this because there are no enough information to reproduce this issue, and because I strongly believe it doesn't really depends on us. Should you have more information or should you be able to exactly pinpoint the issue feel free to reopen it back

**Closed by ste93cry** 2021-02-20 19:47 UTC
Labels: Status: Needs Information, Status: Needs Reproduction, Type: Bug
