### ISSUE TITLE
Issue with custom error template rendering with 500 error

### ISSUE THREAD

**Issue by adrienfr** [getsentry/sentry-symfony#485] opened 2021-04-20 10:54 UTC
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

### Steps to Reproduce

1. Migrate from "sentry/sentry-symfony:4.0" to "sentry/sentry-symfony:4.1"
2. Env is prod (and debug is false)
3. Monolog enabled
4. Generate a 500 error

### Expected Result

This should display my custom error page (templates/bundles/TwigBundle/Exception/error.html.twig)

### Actual Result

The displayed error is the generic one :
<img width="606" alt="Capture d’écran 2021-04-20 à 12 47 24" src="https://user-images.githubusercontent.com/4313077/115383809-916f5d00-a1d6-11eb-8654-c06fd2858836.png">

It seems that `TwigErrorRenderer` is not called anymore.

404 errors are not concerned, the custom error page (templates/bundles/TwigBundle/Exception/error404.html.twig) is correctly displayed (as it was before on "sentry/sentry-symfony:4.0").

Here is my configuration :

**prod/sentry.yml**
```yaml
sentry:
    dsn: "%sentry.dsn%"
    options:
        environment: "%kernel.environment%"
        send_default_pii: true
```

**Comment by ste93cry** [comment] 2021-04-20 10:57
Can you please try setting `sentry.tracing.twig.enabled` to `false`?

**Comment by adrienfr** [comment] 2021-04-20 11:10
This doesn't change anything but it does when setting `sentry.tracing.enabled` to false or :
```yaml
    tracing:
        twig:
            enabled: true
        cache:
            enabled: true
        dbal:
            enabled: false
```
The issue seems to be with dbal tracing instead

**Comment by ste93cry** [comment] 2021-04-20 11:26
Can you please came up with a really small repo reproducing the issue? I have little to no information here to understand what's the issue

**Comment by adrienfr** [comment] 2021-04-20 11:41
> Can you please came up with a really small repo reproducing the issue? I have little to no information here to understand what's the issue

I'll try to create a reproducer.

Could it be a consequence of `doctrine.dbal.logging` not enabled ? (see https://github.com/getsentry/sentry-symfony/pull/426#issue-560680355) ?

**Comment by ste93cry** [comment] 2021-04-20 11:48
>Could it be a consequence of `doctrine.dbal.logging` not enabled ?

I don't think so because we completely changed the way we hook into Doctrine for tracing in respect to that initial comment. However, our method is for sure more invasive because we wrap the driver connection, so if something is happening inside there then understanding the cause without a reproducer may be complicated

**Comment by Jean85** [comment] 2021-04-20 15:23
Can you try to enable Sentry AND the tracing locally, to see if you get any information about your issue?

In either case, do you get any event reported to Sentry, containing any relevant information?

@ste93cry we need to keep in mind #484 as a possible cause.

**Comment by adrienfr** [comment] 2021-04-20 16:56
The event is successfully reported on Sentry, as below:

<img width="971" alt="Capture d’écran 2021-04-20 à 18 50 56" src="https://user-images.githubusercontent.com/4313077/115434781-5f2b2300-a209-11eb-8576-642a4e412a14.png">

> ErrorException: Notice: Trying to get property 'headers' of non-object
> #4 /src/Controller/FlatController.php(181): App\Controller\FlatController::createAction
> #3 /vendor/symfony/http-kernel/HttpKernel.php(157): Symfony\Component\HttpKernel\HttpKernel::handleRaw
> #2 /vendor/symfony/http-kernel/HttpKernel.php(79): Symfony\Component\HttpKernel\HttpKernel::handle
> #1 /vendor/symfony/http-kernel/Kernel.php(196): Symfony\Component\HttpKernel\Kernel::handle
> #0 /public/index.php(31): null

And when enabling debug (`APP_DEBUG=true`), here is the layout:
<img width="1039" alt="Capture d’écran 2021-04-20 à 18 53 54" src="https://user-images.githubusercontent.com/4313077/115435213-e6789680-a209-11eb-8f69-6c673ca9978c.png">

Hope I can generate a reproducer in the evening to help you.

**Comment by adrienfr** [comment] 2021-04-20 20:13
It works when I comment  in TracingDriverConnection->traceFunction() :
```php
// return $callback();
```

The issue might depend on the database configuration, I tried with a new empty database "8.0.21 - MySQL" and it works without commenting `$callback`. But with my local database "10.3.21-MariaDB-1:10.3.21", I have the issue (no custom twig layout displayed).

I will try to duplicate the database settings on a reproducer.

**Comment by adrienfr** [comment] 2021-04-21 07:47
I think I found a possible cause, the issue occurs with package `fresh/doctrine-enum-bundle`.

**Comment by adrienfr** [comment] 2021-04-21 08:04
Here is a simple reproducer, can you tell me if you need anything else? https://github.com/adrienfr/debug-sentry/tree/main

**Comment by Jean85** [comment] 2021-04-21 15:42
I  have issues with your reproducer: it required me to install PDO SQLite (done) but I still get the generic 500 instead of the 404.

**Comment by ste93cry** [comment] 2021-04-21 22:56
I was able to run the reproducer and I indeed can see the issue, although the funny thing is that it appears after reloading the page a second time: with a cache still to be created the error page renders fine 🤔 The good news is that, as you pointed out, the issue seems to be with the DBAL, even though I don't know why, and this is already a starting point. I'm investigating the problem and I will write back once I find the root cause

**Comment by adrienfr** [comment] 2021-04-23 07:51
Thank you @Jean85 and @ste93cry for your time investigating this issue. Tell me if you need anything that could help to fix this, I'll just disable the DBAL tracing for my project for now.

**Comment by ste93cry** [comment] 2021-04-23 19:12
So, I found the root cause and I don't have any idea of how to solve the issue from our side. The problem is that when the [`DoctrineEnumBundle`](https://github.com/fre5h/DoctrineEnumBundle) bundle boots, the custom Doctrine types are registered for each available connection. By loading the connections from the service container, the Sentry SDK gets initialized too because to trace the performance of the SQL queries we have to decorate the connections with our custom implementation. In turn, when the client instance is created the `ErrorListenerIntegration`, `FatalErrorListenerIntegration` and `ExceptionListenerIntegration` integrations are set up. Those integrations register our custom error handler that becomes the active handler and sets as previous handler the Symfony's one. When the `kernel.request` is emitted, the [`DebugHandlersListener::configure()`](https://github.com/symfony/symfony/blob/a9d582d681badfe20f3a4056a310d8abb9f57666/src/Symfony/Component/HttpKernel/EventListener/DebugHandlersListener.php#L74) method is called which does not find the Symfony error handler and does not set the exception handler that calls `$kernel->terminateWithException()`. When our error handler is executed and calls the previous handler, which is the one of Symfony, there is no custom exception handler attached to it and therefore the fallback is to render a default error page. 

Apart from switching away from using our custom error handler to a model where we attach to Monolog to capture the errors (it cannot be done in the current version to not break the BC), I don't think we can do anything here to solve the issue. I therefore opened fre5h/DoctrineEnumBundle#187 to track a potential solution there

As a workaround for the time being though, either you can disable the DBAL tracing (or the whole tracing feature using `sentry.tracing.enabled: false` if you don't care about it) or you can use the [Monolog handler](https://docs.sentry.io/platforms/php/guides/symfony/#monolog-integration) to log errors instead of our custom error handler, which will likely happen officially in the next major version of the bundle anyway.

**Comment by ste93cry** [comment] 2021-04-24 17:42
@adrienfr a new version of the `DoctrineEnumBundle` bundle has been released that should fix the issue. Please give it a try, and feel free to close this issue if it is solved

**Comment by fre5h** [comment] 2021-04-24 17:42
@adrienfr Please please check `7.2.0` tag of enum bundle

**Comment by adrienfr** [comment] 2021-04-24 19:20
Thank you @ste93cry for your help, I would not have been able to identify the root cause as you did!
Thanks @fre5h for the quick fix & release!

Everything works perfectly now, I can close this issue.

**Closed** 2021-04-24 19:21 UTC
Labels: Status: Won't fix
